[www]

listen = 9000
; php-fpm ecoute sur tte les interfaces reseau(0.0.0.0) port 9000

user = www-data
group = www-data

; php-fpm gere les workers dynamiquement, il en demarre qq uns, en ajoute si besoin et ferme si inutilises
; pm = process manager
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3